  $(document).ready(function(){
             $("#index").click(function(){
              $("html").animate({
                left:"1300px"},800,function(){
                  window.location.href="index.html";
                });
             });

  $("#about").click(function(){
              $("html").animate({
                left:"1300px"},800,function(){
                  window.location.href="about.html";
                });
             });
    $("#news").click(function(){
              $("html").animate({
               left:"1300px"},800,function(){
                  window.location.href="news.html";
                });
             });
      $("#pro").click(function(){
              $("html").animate({
                left:"1300px"},800,function(){
                  window.location.href="product.html";
                });
             });
        $("#contact").click(function(){
              $("html").animate({
                left:"1300px"},800,function(){
                  window.location.href="contact.html";
                });
             });
    });